### ISSUE TITLE
Builds fail on some systems because of cffi wheel invalid gzip header

### ISSUE THREAD

**Issue by nrminor** [nrminor/oneroof#12]
On some systems, including in our Docker builds, `pixi install` fails when the `setuptools` build system tries to extract the latest `cffi` wheel archive.

**Comment by nrminor** [comment]
This bug appears to be fixed after the following interventions:

1) Updating `pyproject.toml` with an earlier build version requirement than the current version, 1.17.0:

```toml
[build-system]
requires = ["setuptools >= 40.8.0", "cffi >=1.15.0,!=1.17.0"]
build-backend = "setuptools.build_meta:__legacy__"
```

2) Including the `pixi.lock` file in the repo, which explicitly requests freezes `cffi` with version 1.16.0.

3) In the Dockerfile, running `pixi install` with the `--frozen` flag to only pull versions explicitly stated in `pixi.lock` rather than looking for newer versions.
